### ISSUE TITLE
Implement pagination

### ISSUE THREAD

**Issue by justinpearson** [scalableinternetservices/Luber#106]
For load-testing, it will be important to not display a million rentals on a single page.

Places that require pagination:

- list of all rentals: http://0.0.0.0:3000/rentals
- a user's overview: http://0.0.0.0:3000/users/1/overview
- a user's rentals: http://0.0.0.0:3000/users/1/rentals
- a user's cars: http://0.0.0.0:3000/users/1/cars

**Comment by carsonkk** [comment]
Also http://0.0.0.0:3000/users/1/rentals is gonna take some thought, since it currently has both rentals as an owner and renter. Not sure how to handle that without breaking it into two different pages, one as owner, one as renter, or interleaving the two
