### ISSUE TITLE
Minor edit to 'create rental post' page

### ISSUE THREAD

**Issue by justinpearson** [scalableinternetservices/Luber#52]
As owner, when I "create rental post":

- should see list of cars, not car id
- date validation: end date after start date
- no renter
- no owner (i am the owner)
- price field validation: 2 dec pts max, display like $

**Comment by carsonkk** [comment]
Also:
- Add terms field
- validate license plate length/symbols
- set status to 0 by default

**Comment by justinpearson** [comment]
Partially addressed by PR #80: 

- validate license plate length/symbols
- set status to 0 by default

**Comment by justinpearson** [comment]
Kyle fixed this in commit 56384c2.
