### ISSUE TITLE
Don't let users see each others' details

### ISSUE THREAD

**Issue by justinpearson** [scalableinternetservices/Luber#60]
Example: as user2, I shouldn't be able to see details of user1's car, even if I have his car's URL.

**Comment by Heronalps** [comment]
@masoug Does this framework solve this issue already?

**Comment by masoug** [comment]
at this point, anyone can see/update/delete another's cars. but they can not modify or delete another users rental post or profile.

**Comment by justinpearson** [comment]
Sammy fixed this in dc5651c0992930bfafdc42952fe9b21a75ed25a3 .
