### ISSUE TITLE
Fix any/all issues with the production deployment

### ISSUE THREAD

**Issue by carsonkk** [scalableinternetservices/Luber#66]
Make sure the project runs the same in production as it does in dev. This includes:

- Images should load
- Favicon should load
- Javascript components function properly
- Data is stored/deleted from the database correctly
- Any other issues that may arise

**Comment by Heronalps** [comment]
Working on it.

**Comment by Heronalps** [comment]
I have browsed through Luber in production and seems like it's in line with dev. Should we close it now or keep it as an ongoing effort?
