### ISSUE TITLE
Car: license plate validation should permit length btwn 1 and 7

### ISSUE THREAD

**Issue by justinpearson** [scalableinternetservices/Luber#85]
(to allow custom plates). And no regex.

**Comment by carsonkk** [comment]
I went back to the dmv's website to check and found the following:
- 2 to 7 characters that aren't spaces (can't have 0 or 1 non-space characters)
- Can be letters, numbers, or spaces
- Letters should be sent to uppercase when stored

So all the following are valid (where _ is a space):
_A____4
54FEB__
AAAAAAA
1234567

The constraints are actually much more complicated (there exist "half-spaces", symbols, ambigous limits on what is "appropriate" or not, basically they can reject anything they want). But those are the hard limits

**Comment by justinpearson** [comment]
Nice sleuthing! This is very helpful.
