### ISSUE TITLE
Rental: Comment out the geo-coding lines (and save demo branch)

### ISSUE THREAD

**Issue by justinpearson** [scalableinternetservices/Luber#88]

**Comment by carsonkk** [comment]
Im working on restyling the geo-code stuff, what is this referring to exactly?

**Comment by justinpearson** [comment]
By "geo-coding" lines, I mean in the model `rental.rb` we have

      geocoded_by :start_location,  latitude: :start_latitude, longitude: :start_longitude
      after_validation :geocode, if: ->(obj){ obj.start_location.present? }

However, for load-testing, we probably don't want to use this, because it uses the network and is slow. 

We should save / tag this functionality for the in-class demo of the site however.

**Comment by carsonkk** [comment]
Rather than comment out the lines, we should either
- Wrap them in something that will only run them on dev/prod environments and not the tsung environment
- Or if that isn't viable, use the local environment variables field to control it, changing the value if we are/aren't in tsung

**Comment by justinpearson** [comment]
I agree, it would be very nice to disable the Google API calls automatically if Tsung is being used. Better than keeping a possibly-old version of code to use for the class demo. On the other hand, I think there's no shame in showing a screen recording of our App with the Google maps when we do our presentation. That would reduce a lot of "demo stress". I would be happy to make the screen recording.
