### ISSUE TITLE
Make seed file that uses SQL to create a huge db.

### ISSUE THREAD

**Issue by justinpearson** [scalableinternetservices/Luber#98]
Like, 10,000 users, cars, tags, rentals.

**Comment by carsonkk** [comment]
A couple thoughts I had about this:
- We're gonna want to make this interesting and have a lot of variety in number of rentals, cars, dates etc, so debugging with say 10/15 users then scaling when its solid is gonna be important
- The way the site is right now it will be unusable. Say each user makes two rental posts, and then we try to go to /rentals, it will try to load thousands of posts all on one page. Basically the users#cars, users#rentals, and rentals#index pages all need some pagination logic so there are pages

**Comment by justinpearson** [comment]
I agree that pagination will be important. In the example report that Bryce sent, pagination was the first improvement the team performed and it helped a lot. We might as well implement pagination before heavy Tsung testing; I'll make an issue for it.
